create database qna;
USE  qna;
CREATE TABLE  users (
USERID INTEGER AUTO_INCREMENT PRIMARY KEY,
USERNAME VARCHAR(32),
    EMAILID VARCHAR(32),
    PASS VARCHAR(12),
    ROLE INTEGER);

USE QNA;
DROP TABLE TAGS;
CREATE TABLE TAGS (
     TAGID INTEGER AUTO_INCREMENT PRIMARY KEY,
     TOPIC VARCHAR(32),
     CREATED_TIME TIMESTAMP,
     TIME_LAST_REFERRED TIMESTAMP,
     USAGE_COUNT BIGINT);

USE QNA;
DROP TABLE QUESTIONS;
CREATE TABLE QUESTIONS (
QUESTION_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
TAG VARCHAR(64),
QUESTION VARCHAR(128),
CREATED_TIME TIMESTAMP,
TIME_LAST_REFERRED TIMESTAMP,
USAGE_COUNT BIGINT);

 CREATE TABLE ANSWERS  (
     ANSWER_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
     QUESTION_ID INTEGER,
     FOREIGN KEY (QUESTION_ID)
     REFERENCES QUESTIONS(QUESTION_ID),
     CREATED_TIME TIMESTAMP
     );

